import{S,a as B,i as d}from"./assets/vendor-CwlUggAG.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const n={searchGallery:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".load-btn-js")},q=({largeImageURL:t,webformatURL:r,tags:a,likes:o,views:e,comments:s,downloads:c})=>`<li class="gallery-item">
             <a href ="${t}">
             <img class="gallery-img" src="${r}" alt="${a}"/> 
             </a> 

            <ul class = "img-info-list">
            <li class="img-info-item"><span class="img-item-desc">Likes</span> ${o}</li>
            <li class="img-info-item"><span class="img-item-desc">Vievs </span> ${e}</li>
            <li class="img-info-item"><span class="img-item-desc">Comments </span> ${s}</li>
            <li class="img-info-item"><span class="img-item-desc">Downloads</span> ${c}</li>
            </ul>

          </li>`,v=new S(".gallery a",{captionsData:"alt",captionDelay:250}),y=t=>{const r=t.map(a=>q(a)).join("");n.searchGallery.insertAdjacentHTML("beforeend",r),v.refresh()},h=()=>n.searchGallery.innerHTML="",g=()=>{n.loader.classList.remove("is-hidden")},p=()=>{n.loader.classList.add("is-hidden")},L=()=>{n.loadMoreBtn.classList.remove("is-hidden")},l=()=>{n.loadMoreBtn.classList.add("is-hidden")},w="53395208-f197eaad794bdfcff5070dc5e",P="https://pixabay.com/api/",f=15,b=async(t,r)=>{const a={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:f},o=await B.get(P,{params:a}),{data:e}=o;return e},m={form:document.querySelector(".form"),searchGallery:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".load-btn-js")};let i=1,u="";const M=async t=>{t.preventDefault(),l();const{target:r}=t,a=r.elements["search-text"].value.trim();if(a===""){d.error({message:"Pleace enter what are you searching for",position:"topRight"});return}u=a,i=1,g();try{const{hits:o,totalHits:e}=await b(u,i);if(o.length===0){h(),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l();return}h(),y(o),i*f>=e?(l(),d.info({message:"Were sorry, but you've reached the end of search results",position:"topRight"})):L()}catch(o){console.log(o)}finally{p(),m.form.reset()}},G=async()=>{i+=1,g();try{const{hits:t,totalHits:r}=await b(u,i);if(t.length===0){l();return}y(t),i*f>=r?(d.info({message:"Were sorry, but you've reached the end of search results",position:"topRight"}),l()):L();const e=m.searchGallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(t){console.log(t)}finally{p()}};m.form.addEventListener("submit",M);m.loadMoreBtn.addEventListener("click",G);
//# sourceMappingURL=index.js.map
