import{S as L,a as S,i as d}from"./assets/vendor-CwlUggAG.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const i={searchGallery:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".load-btn-js")},b=({largeImageURL:r,webformatURL:s,tags:o,likes:a,views:e,comments:t,downloads:n})=>`<li class="gallery-item">
             <a href ="${r}">
             <img class="gallery-img" src="${s}" alt="${o}"/> 
             </a> 

            <ul class = "img-info-list">
            <li class="img-info-item"><span class="img-item-desc">Likes</span> ${a}</li>
            <li class="img-info-item"><span class="img-item-desc">Vievs </span> ${e}</li>
            <li class="img-info-item"><span class="img-item-desc">Comments </span> ${t}</li>
            <li class="img-info-item"><span class="img-item-desc">Downloads</span> ${n}</li>
            </ul>

          </li>`,B=new L(".gallery a",{captionsData:"alt",captionDelay:250}),y=r=>{const s=r.map(o=>b(o)).join("");i.searchGallery.insertAdjacentHTML("beforeend",s),B.refresh()},f=()=>i.searchGallery.innerHTML="",h=()=>{i.loader.classList.remove("is-hidden")},g=()=>{i.loader.classList.add("is-hidden")},q=()=>{i.loadMoreBtn.classList.remove("is-hidden")},m=()=>{i.loadMoreBtn.classList.add("is-hidden")},w="53395208-f197eaad794bdfcff5070dc5e",v="https://pixabay.com/api/",p=async(r,s)=>{const o={key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15},a=await S.get(v,{params:o}),{data:e}=a;return e},l={form:document.querySelector(".form"),searchGallery:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".load-btn-js")};let c=1,u="";const M=async r=>{r.preventDefault(),m();const{target:s}=r,o=s.elements["search-text"].value.trim();if(o===""){d.error({message:"Pleace enter what are you searching for",position:"topRight"});return}u=o,c=1,h();const{hits:a,totalHits:e}=await p(u,c);try{if(a.length===0){f(),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),m();return}f(),y(a),q()}catch(t){console.log(t)}finally{g(),l.form.reset()}},P=async()=>{c+=1,h();try{const{hits:r,totalHits:s}=await p(u,c);y(r),c*15>=s&&(d.error({message:"Were sorry, but you've reached the end of search results",position:"topRight"}),m());const e=l.searchGallery.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}catch(r){console.log(r)}finally{g()}};l.form.addEventListener("submit",M);l.loadMoreBtn.addEventListener("click",P);
//# sourceMappingURL=index.js.map
